version: '3.7'

services:
  apache:
    build:
      dockerfile: Dockerfile
      context: .
    image: mbissonho/simple-php-server
    container_name: simple-php-server
    command: >
            /bin/sh -c "./get_ci_system_dir.sh && 
            /usr/sbin/apache2ctl -D FOREGROUND"
    restart: always
    ports:
      - '80:80'
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
